# config parameters
name: "" # default name for the experiment, "" means logger (eg. wandb) will generate a unique name
seed: 52 # seed for random number generators in pytorch, numpy and python.random
num_workers: 16 # number of subprocesses to use for data loading.

# defaults
defaults:
  - latent: default_gp
  - visualize:
      - distribution
      - clustering
      - brain
      - nonlinear
  - _self_